language: cpp
compiler: gcc
sudo: require
dist: trusty

install:
  - wget -c "https://raw.githubusercontent.com/probonopd/linuxdeployqt/feature/upstream-qt/qtdownload"
  - . qtdownload
  - QTSUBCOMPONENT=icu ; . qtdownload
# - sudo add-apt-repository --yes ppa:xqms/opencv-nonfree
# - sudo apt-get update 
# - sudo apt-get -y install libopencv-nonfree-dev
  - sudo apt-get -y install libopencv-dev
  - find /usr/include -name "photo.hpp" # /usr/include/opencv2/photo/photo.hpp
  - find /usr/lib -name "libopencv_core.so"
  - sudo mkdir -p /usr/local/lib/ ; sudo cp $(dirname $(find /usr/lib -name "libopencv_core.so"))/libopencv_* /usr/local/lib/
  
script:
  - qmake CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - # curl --upload-file Face_recognize*.AppImage https://transfer.sh/Face_recognize-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Face_recognize*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
